# Generated by Django 6.1 on 2026-08-18 17:36

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=airport.models.airplane_image_file_path
            ),
        ),
    ]
